path:
  id:
    name: id
    in: path
    description: example model ID
    required: true
    example: 123
    type: string
    maxLength: 32
    pattern: '^[a-zA-Z0-9-_]+$'

query:
  filter:
    name: filter
    in: query
    description: filter for example model
    example: 'status=active'
    type: string
    maxLength: 100
    pattern: '^[a-zA-Z0-9-_=]+$'
  page:
    name: page
    in: query
    description: page pagination for example model
    example: 1
    default: 1
    type: number
    maximum: 300
  perPage:
    name: perPage
    in: query
    description: Count items per page. Pagination for example model
    example: 15
    default: 15
    type: number
    maximum: 300